FROM dockerhub.planetek.it/ubuntu-maven-git-muleesb:base
LABEL maintainer.name="ilias ioannou" \
      maintainer.email="ioannou@planetek.gr"

WORKDIR /
RUN git clone https://teamEreticoTfs:hIEMK-i=d@tfs.planetek.it/Planetek%20Hellas/pkh111_EOSAI/_git/pkh111_EOSAI_ESB /src

WORKDIR src/ESB/water_quality
RUN cp -r src/main/resources/legenda /legenda
RUN mvn dependency:resolve
WORKDIR /src
